# Generated by Django 4.2.9 on 2024-08-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0002_questions_created_by'),
        ('quiz_management', '0002_quiz_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(related_name='quiz', to='question_management.questions'),
        ),
    ]
