# Generated by Django 4.2.9 on 2024-08-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
        ('quiz_management', '0002_quiz_created_by'),
        ('question_management', '0002_questions_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='question_management.option')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quiz_management.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user_management.student')),
            ],
            options={
                'unique_together': {('quiz', 'student', 'option')},
            },
        ),
    ]
