# Generated by Django 4.2.9 on 2024-08-30 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_management', '0002_questions_created_by'),
        ('answer_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersubmission',
            name='is_correct',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='question_management.option'),
        ),
    ]
