# Generated by Django 4.2.9 on 2024-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_submission', '0002_alter_answersubmission_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersubmission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
