# Generated by Django 5.0.3 on 2024-09-03 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_submission', '0003_alter_answersubmission_is_correct'),
        ('question_management', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='question_management.questions'),
        ),
    ]
