# Generated by Django 4.2.9 on 2024-09-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('answer_submission', '0004_answersubmission_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.teacher'),
        ),
    ]
